export const BRAZILIAN_STATES = [
  { value: 'AC', display: 'Acre'},
  { value: 'AL', display: 'Alagoas'},
  { value: 'AP', display: 'Amapá'},
  { value: 'AM', display: 'Amazonas'},
  { value: 'BA', display: 'Bahia'},
  { value: 'CE', display: 'Ceará'},
  { value: 'DF', display: 'Distrito Federal'},
  { value: 'ES', display: 'Espírito Santo'},
  { value: 'GO', display: 'Goiás'},
  { value: 'MA', display: 'Maranhão'},
  { value: 'MT', display: 'Mato Grosso'},
  { value: 'MS', display: 'Mato Grosso do Sul'},
  { value: 'MG', display: 'Minas Gerais'},
  { value: 'PA', display: 'Pará'},
  { value: 'PB', display: 'Paraíba'},
  { value: 'PR', display: 'Paraná'},
  { value: 'PE', display: 'Pernambuco'},
  { value: 'PI', display: 'Piauí'},
  { value: 'RJ', display: 'Rio de Janeiro'},
  { value: 'RN', display: 'Rio Grande do Norte'},
  { value: 'RS', display: 'Rio Grande do Sul'},
  { value: 'RO', display: 'Rondônia'},
  { value: 'RR', display: 'Roraima'},
  { value: 'SC', display: 'Santa Catarina'},
  { value: 'SP', display: 'São Paulo'},
  { value: 'SE', display: 'Sergipe'},
  { value: 'TO', display: 'Tocantins'}
]